name: .NET Build

on:
  pull_request:

env:
  SOLUTION_FILE_PATH: NeosmartpenSDK.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: dotnet build ${{env.SOLUTION_FILE_PATH}} --configuration ${{env.BUILD_CONFIGURATION}} --no-restore
